# Generated by Django 5.2 on 2025-11-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_info_porichalok'),
    ]

    operations = [
        migrations.AddField(
            model_name='porichalok',
            name='title',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
