# Generated by Django 5.2 on 2025-11-05 04:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_porichalok_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porichalok',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
