# Generated by Django 5.2.7 on 2025-11-14 15:08

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_headteacher_notice_widget_info_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaddhomikTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField()),
                ('image', models.FileField(upload_to='teachers')),
                ('text', django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='headteacher',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='porichalok',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='info',
            name='about_school',
            field=django_ckeditor_5.fields.CKEditor5Field(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='school_image',
            field=models.FileField(default=False, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='base.category'),
        ),
    ]
