# Generated by Django 5.2.7 on 2025-11-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_maddhomikteacher_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='school_image_sec',
            field=models.FileField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
