# Generated by Django 5.2.9 on 2025-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_info_school_image_sec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='gellery')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='headteacher',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='maddhomikteacher',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='porichalok',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ['id']},
        ),
    ]
