# Generated by Django 5.2.9 on 2025-12-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_gellery_news_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='calenders')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
